### ISSUE TITLE
ImageNet-trainded resnet50/resnet101 weights

### ISSUE THREAD

**Issue by DeepAlchemist** [HobbitLong/CMC#10]
Hi, thank you for your code. Would you please provide a download link of ImageNet-trained resnet50/resnet101 weights?

**Comment by asdfqwer2015** [comment]
Same issue.

**Comment by HobbitLong** [comment]
Hi, @DeepAlchemist  and @asdfqwer2015 ,

The weights can be found via DropBox here:
https://www.dropbox.com/sh/vheozqh7qi51azy/AAC9OBgWFAYyjFRkUJTxJVpma?dl=0

**Comment by asdfqwer2015** [comment]
Thanks for your quick reply.
:)

**Comment by DeepAlchemist** [comment]
Thank you.

**Comment by HobbitLong** [comment]
Update:

These weights are compatible with code under the branch of `old_submission`. It could be compatible with the master branch but requires some work.

For the new weights, please refer to the new readme.
