### ISSUE TITLE
High Values of Z_L and Z_ab

### ISSUE THREAD

**Issue by adithya-subramanian** [HobbitLong/CMC#12]
Hi,
   Thanks for open-sourcing your work, I have been trying to use CMC on my custom toy dataset which has 2 views (Image (3D), Sensor view (3D)) I'm able to run the model successfully but the Z for view 1 and view 2 is being set to 119973150195712.

I made sure to use L2 norm around the final features from each of the alexnet halfs but I'm really not sure why the Z values are being initialized to such a high value. I kept the nce_m,nce_k and nce_t to the same as that of your code. 

Please, can you help me with the same? Thank you

**Comment by HobbitLong** [comment]
Hi,

How large is your dataset? Z is a Monte Carlo estimate of the partition function of the softmax. It should be proportional to your dataset.

Do you run into similar problem with ImageNet data or just your own data?

**Comment by adithya-subramanian** [comment]
Hi,
   Thanks for your reply I understand the fact that it is a Monte Carlo estimate, my dataset has 700 images. I didn't run into the same issues in imagenet.

**Comment by HobbitLong** [comment]
Given what you provided, I cannot have a better guess about the issue.

Probably you do not need NCE as your dataset is very small. Maybe you can just try softmax instead?

**Comment by adithya-subramanian** [comment]
I am basically trying to understand the convergence of nce to softmax and experimenting the same with different samples sizes. What do you think is the appropriate sample size for the convergence of nce gradients to softmax gradients.

**Comment by HobbitLong** [comment]
NCE is an approximation for high dimensional softmax.

One possible issue with NCE for less data is that, when you sample large amount of negatives (assume if you are doing k with 4096) and you only have 700 images, the true "positive" will be counted as negative by several times. This means the network is misleadingly to classify positive samples as negatives with a significant weight, which is wrong and will overwhelmed the correct gradient.
