### ISSUE TITLE
MoCo pre-trained weights

### ISSUE THREAD

**Issue by JiahuanChen** [HobbitLong/CMC#19]
Would you please share the MoCo pre-trained weights?

**Comment by HobbitLong** [comment]
Hi, @JiahuanChen , 

I do not have the MoCo model trained on the full ImageNet dataset.  I only have a model trained on a subset of 100 classes. 

If I get some chance to train MoCo model on the full ImageNet dataset sometime in the future, I will share the weights.

**Comment by Magauiya** [comment]
Firstly, thank you for sharing the implementations of other methods too. It would great if you upload checkpoints of pre-trained MoCo and Inst-Dis (even if they are trained on a part of ImageNet, e.g. Imagenet100k).

**Comment by HobbitLong** [comment]
@JiahuanChen , @Magauiya , updated! Please see README.
