### ISSUE TITLE
About the category list of ImageNet-100 subset

### ISSUE THREAD

**Issue by szq0214** [HobbitLong/CMC#21]
Hi @HobbitLong, thanks for your great work and also sharing the code. I guess the ImageNet-100 is not a conventional subset so I wonder if you can share the list since we also don't have enough resources to run on the full ImageNet ==.

**Comment by YanruoYang** [comment]
Same issue：I have tried the tiny-imagenet-100-A dataset from https://tiny-imagenet.herokuapp.com/, is it same as the  ImageNet-100 metioned in the README?
Btw, I follow the guide to train the dataset using MoCo, but the test_acc top1 is about 2.5%, and the train_acc top 1% is about 59%, I don't know which part of the exp maybe be wrong. Could you show some val dataset format or test_set acc curvey?

**Comment by HobbitLong** [comment]
Hi, please find the list below:

`n02869837
n01749939
n02488291
n02107142
n13037406
n02091831
n04517823
n04589890
n03062245
n01773797
n01735189
n07831146
n07753275
n03085013
n04485082
n02105505
n01983481
n02788148
n03530642
n04435653
n02086910
n02859443
n13040303
n03594734
n02085620
n02099849
n01558993
n04493381
n02109047
n04111531
n02877765
n04429376
n02009229
n01978455
n02106550
n01820546
n01692333
n07714571
n02974003
n02114855
n03785016
n03764736
n03775546
n02087046
n07836838
n04099969
n04592741
n03891251
n02701002
n03379051
n02259212
n07715103
n03947888
n04026417
n02326432
n03637318
n01980166
n02113799
n02086240
n03903868
n02483362
n04127249
n02089973
n03017168
n02093428
n02804414
n02396427
n04418357
n02172182
n01729322
n02113978
n03787032
n02089867
n02119022
n03777754
n04238763
n02231487
n03032252
n02138441
n02104029
n03837869
n03494278
n04136333
n03794056
n03492542
n02018207
n04067472
n03930630
n03584829
n02123045
n04229816
n02100583
n03642806
n04336792
n03259280
n02116738
n02108089
n03424325
n01855672
n02090622
`

Testing curve of MoCo:
![moco](https://user-images.githubusercontent.com/29867600/69910720-07a2d200-13de-11ea-8f6c-c29fce36beca.png)

**Comment by HobbitLong** [comment]
@szq0214 @YanruoYang . For MoCo on ImageNet-100, setting `--alpha 0.99` gives slightly better results (shown above) than `--alpha 0.999`, which gives an accuracy of around 72.0%.

**Comment by ChongjianGE** [comment]
@HobbitLong 
Hi, thank you for providing the detailed list.
Actually, there are 1300 images in one single sub-file. I wonder whether you use all of the images in ImageNet-100 subset or not?

**Comment by qsunyuan** [comment]
I found two versions of Imagenet100 dataset.
I was so confused which one should I choose. 

Vesions 1:
<https://www.kaggle.com/ambityga/imagenet100> or <https://github.com/arthurdouillard/incremental_learning.pytorch/tree/master/imagenet_split>

Vesions 2:
as disscussed above. the label index.

Hope to get ur suggestions early.

Thx.

**Comment by HobbitLong** [comment]
Hi, @qsunyuan , I think either one is OK. If you want to directly compare with numbers in our CMC paper, you could use the one this repo provides.
