### ISSUE TITLE
How to prevent an element in the enqueue come from the same sample as the query?

### ISSUE THREAD

**Issue by HebutAIer** [HobbitLong/CMC#27]
How to prevent an element in the enqueue come from the same sample as the query， especially when the dataloader‘s param "shuffle" is True?

Thank you

https://github.com/HobbitLong/CMC/blob/783bf95af490f0977028c33529e979fa55b9cfff/NCE/NCEAverage.py#L178

**Comment by HobbitLong** [comment]
Hi, @HebutAIer ,

That case can only happen at the beginning of each epoch. It's pretty sparse in general. 

It should not affect the performance much if your dataset is big enough, e.g., ImageNet. But if your dataset is small, you might consider customizing your dataloader a bit to avoid it.
