### ISSUE TITLE
the initial value of memory  in Memory Bank of InsDis and CMC

### ISSUE THREAD

**Issue by lhcalibur** [HobbitLong/CMC#33]
Why initialize memory value this way? Thanks!
```python
stdv = 1. / math.sqrt(inputSize / 3)
self.register_buffer('memory', torch.rand(self.queueSize, inputSize).mul_(2 * stdv).add_(-stdv))
```

**Comment by Eddiesyn** [comment]
I also don't know the exact reason. Hope maybe someone could give an explanation. I guess it may be an approximation of initialize the memory bank with unit random vectors. The original paper InstDiscrimination's implementation uses exactly also this way to initialize memory bank.

**Comment by HobbitLong** [comment]
Hi, @lhcalibur, 

Good question!

Suppose you sample each dimension `x` uniformly from `[-a, a]`, you want `inputSize * E[x^2] = 1` to guarantee that the expectation of the norm of the random vector is one. Then the computation is easy.
