### ISSUE TITLE
Augmenting images at the evaluation of downstream classification task

### ISSUE THREAD

**Issue by dandelin** [HobbitLong/CMC#34]
https://github.com/HobbitLong/CMC/blob/58d06e9a82f7fea2e4af0a251726e9c6bf67c7c9/eval_moco_ins.py#L372-L397

If I understand the inner work of `eval_moco_ins.py` correctly, the code seems training the downstream task (single FC) using augmented images (train_transform == 'CJ').

This augmentation process not only slows down the training speed of the downstream task but also seems to violate the purpose of evaluation (_Then we freeze the features and train a supervised linear classiﬁer_, said in MoCo paper).

Isn't it right to save the center-cropped average pooled features and perform FC training on those fixed features?

**Comment by HobbitLong** [comment]
Hi, @dandelin ,

I think MoCo paper means what the code is currently doing: _freeze the network weights, but you can do different crop augmentation for each epoch, like the supervised case_.

As for accelerating the linear evaluation process, you are right, and you can cache the features of several random crops of each image, and just train the logistic regression layer.

**Comment by dandelin** [comment]
@HobbitLong 
Thanks for the reply :)
