### ISSUE TITLE
TenCrop Results

### ISSUE THREAD

**Issue by littlevegetablechicken** [HobbitLong/CMC#36]
Is there any ten crop results?  As I know,  some methods will improve a lot with ten crop, but some may only improve a little. I wonder how much improvement can be get with ten crop in CMC.

**Comment by HobbitLong** [comment]
@littlevegetablechicken , I don't have. You can use the weights I uploaded for MoCo, InsDis, and CMC to test the 10 crop results.

I will close this issue, but feel free to reopen and please keep me posted if you have some finding :)
