### ISSUE TITLE
Unable to run pre-trained models

### ISSUE THREAD

**Issue by jlindsey15** [HobbitLong/CMC#44]
Hello,

Thanks for making this code available.  I am trying to run the pertained alexnet model (downloaded from the Dropbox link) with the following command:

python LinearProbing.py --dataset imagenet --data_folder /share/ctn/users/jwl2182/imagenet_data --save_path . --model_path /home/jwl2182/CMC/CMC_alexnet.pth --model alexnet --learning_rate 0.1 --layer 5 --tb_path /home/jwl2182/CMC/tb --gpu 0

But I get the following error.  Any ideas what might be happening?

RuntimeError: Error(s) in loading state_dict for MyAlexNetCMC:
        Unexpected key(s) in state_dict: "encoder.module.l_to_ab.conv_block_1.1.num_batches_tracked", "encoder.module.l_to_ab.conv_block_2.1.num_batches_tracked", "encoder.module.l_to_ab.conv_block_3.1.num_batches_tracked", "encoder.module.l_to_ab.conv_block_4.1.num_batches_tracked", "encoder.module.l_to_ab.conv_block_5.1.num_batches_tracked", "encoder.module.l_to_ab.fc6.1.num_batches_tracked", "encoder.module.l_to_ab.fc7.1.num_batches_tracked", "encoder.module.ab_to_l.conv_block_1.1.num_batches_tracked", "encoder.module.ab_to_l.conv_block_2.1.num_batches_tracked", "encoder.module.ab_to_l.conv_block_3.1.num_batches_tracked", "encoder.module.ab_to_l.conv_block_4.1.num_batches_tracked", "encoder.module.ab_to_l.conv_block_5.1.num_batches_tracked", "encoder.module.ab_to_l.fc6.1.num_batches_tracked", "encoder.module.ab_to_l.fc7.1.num_batches_tracked".

**Comment by HobbitLong** [comment]
Using pytorch >= 1.0 to load the weights will solve this problem.
