### ISSUE TITLE
Pre-trained weights for linear classifier available?

### ISSUE THREAD

**Issue by rgeirhos** [HobbitLong/CMC#47]
Hey there, thanks for the well-documented code!

Quick question: Am I correctly assuming that in order to evaluate the model on the 1,000-class ImageNet validation dataset one has to train the linear classifier first (using `LinearProbing.py`)? If so, would it be possible to release pre-trained weights for the classifier as well, such that one can use `classifier.load_state_dict(checkpoint['classifier'])`?

**Comment by HobbitLong** [comment]
@rgeirhos, currently not available. It will take several hours to train a new one.

**Comment by rgeirhos** [comment]
Thanks for your reply.
