### ISSUE TITLE
Support for DistributedDataParallel

### ISSUE THREAD

**Issue by chihyaoma** [HobbitLong/CMC#5]
Hi 

Thank you for sharing this great work with us. 

I saw that you have `spawn` in the code, thus I am wondering your plan to release the code for supporting `DistributedDataParallel`. In particular, I am curious how do you sync the memory bank for _L_ and _ab_, _e.g.,_ in `self.register_buffer('memory_ab')` during training.

Thank you :)

**Comment by HobbitLong** [comment]
Hi,

Good question!

I used DataParallel for the pretraining stage instead. Distributed training is for the linear classifier stage. I am also interested in synchronizing the memory across different GPUs, let me know if you figure out a solution :)

**Comment by HobbitLong** [comment]
@chihyaoma 

I have updated the repo for distributed training of linear classifiers, if that could be helpful

I am closing it since it's not an issue. Feel free to reopen it, though.
