### ISSUE TITLE
Weight shape in Linear classifier

### ISSUE THREAD

**Issue by bfshi** [HobbitLong/CMC#52]
Hi! Congrats on the work! 

I may find something weird here. 

https://github.com/HobbitLong/CMC/blob/58d06e9a82f7fea2e4af0a251726e9c6bf67c7c9/models/LinearModel.py#L82

nChannels here should be 512 * width instead of 2048 * width? For example, for ResNet18v1, each view has 256 channel, so that's 512 in total

**Comment by HobbitLong** [comment]
Hi, @bfshi, good catch! This should only work for ResNet-50. Please adapt it to 512 if you wanna use ResNet18.
