### ISSUE TITLE
Gpu memory heavy on gpu0

### ISSUE THREAD

**Issue by tankche1** [HobbitLong/CMC#54]
Hi, thanks for sharing the code.
I notice that if I use 8 GPU, due to NCEAverage.cuda(), the first gpu will use like 10500MB while other gpu will use like only 4000MB. 
Can't run a ResNet width 2 CMC on an eight 2080Ti machine. 
Any idea to balance? So that I can use deeper model and higher dimension.

**Comment by HobbitLong** [comment]
Try another implementation here: https://github.com/HobbitLong/PyContrast/tree/master/pycontrast, which should save you some memory thanks to distributed data parallel
