### ISSUE TITLE
The normalization of ImageNet is different from the mainstream setting.

### ISSUE THREAD

**Issue by everange-ustc** [HobbitLong/CMC#6]
Does the version of the torchvision impact the experimental setting, and which version should be used in the experiments?

**Comment by HobbitLong** [comment]
It shouldn't except for some possible Float/Double issue, see [here](https://github.com/HobbitLong/CMC/issues/3).

The difference of normalization is due to the color space, where we work on Lab space rather than the standard RGB.

**Comment by everange-ustc** [comment]
Why choose lab space rather than standard RGB? I did not find any explanation about this in the paper.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Yonglong Tian <notifications@github.com>
发送时间: Tuesday, July 23, 2019 4:25:58 PM
收件人: HobbitLong/CMC <CMC@noreply.github.com>
抄送: everange <chencoriver@live.cn>; Author <author@noreply.github.com>
主题: Re: [HobbitLong/CMC] The normalization of ImageNet is different from the mainstream setting. (#6)


It shouldn't except for some possible Float/Double issue, see here<https://github.com/HobbitLong/CMC/issues/3>.

The difference of normalization is due to the color space, where we work on Lab space rather than the standard RGB.

―

**Comment by HobbitLong** [comment]
We want to maximize Mutual Information between two different views, where we hope these two views can be as uncorrelated as possible. Therefore we prefer Lab space.

**Comment by HobbitLong** [comment]
I am closing it now due to inactivity. Feel free to reopen if you would like to discuss more
